//создание таблицы
CREATE TABLE comments (
                          id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          post TEXT,
                          date TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                          content TEXT,
                          last_update TIMESTAMP(0)
)

//Добавление записей в таблицу
insert into comments (post, date, content)
VALUES ('это пробный комментарий', now(), '12123.jpg')

//Удаление данных из таблицы и обнуление автоинкремента
TRUNCATE TABLE comments RESTART IDENTITY;